# Generated by Django 5.2.8 on 2025-11-22 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tikket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.IntegerField()),
                ('departure_time', models.DateTimeField(auto_now_add=True)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('base_price', models.IntegerField()),
                ('aircraft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_tikket.aircraft')),
                ('airline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_tikket.airline')),
                ('departure_airport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_tikket.airport')),
            ],
        ),
    ]
