# Generated by Django 5.2.8 on 2025-11-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tikket', '0002_ticket_booking_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
