# Generated by Django 5.2.8 on 2025-11-22 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tikket', '0003_flights_delete_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=100)),
                ('seat_class', models.CharField(max_length=100)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_tikket.aircraft')),
            ],
        ),
    ]
