# Generated by Django 5.2.8 on 2025-11-22 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tikket', '0004_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_tikket.flights')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_tikket.seat')),
            ],
        ),
    ]
